// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0JuH1GKxzNxuS0OmQn3PWsbtN9GUsV6g',
    appId: '1:759100098277:web:727570fd1b481cf2c2360c',
    messagingSenderId: '759100098277',
    projectId: 'nyzoride-69ab6',
    authDomain: 'nyzoride-69ab6.firebaseapp.com',
    storageBucket: 'nyzoride-69ab6.firebasestorage.app',
    measurementId: 'G-JS33JVMYXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeUXWCR972pTy5Id2g6uHdPDd26w3eqHw',
    appId: '1:759100098277:android:61e70bc10eab8edac2360c',
    messagingSenderId: '759100098277',
    projectId: 'nyzoride-69ab6',
    storageBucket: 'nyzoride-69ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWxOdmQHIt98P0yNmmgSKNg7-yCuWeREI',
    appId: '1:759100098277:ios:ad36343b98ee3321c2360c',
    messagingSenderId: '759100098277',
    projectId: 'nyzoride-69ab6',
    storageBucket: 'nyzoride-69ab6.firebasestorage.app',
    iosBundleId: 'com.example.nyzoCaptain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWxOdmQHIt98P0yNmmgSKNg7-yCuWeREI',
    appId: '1:759100098277:ios:759cd9c74dc4d0bfc2360c',
    messagingSenderId: '759100098277',
    projectId: 'nyzoride-69ab6',
    storageBucket: 'nyzoride-69ab6.firebasestorage.app',
    iosBundleId: 'com.example.mdDriverApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0JuH1GKxzNxuS0OmQn3PWsbtN9GUsV6g',
    appId: '1:759100098277:web:1f28bdc7943778cfc2360c',
    messagingSenderId: '759100098277',
    projectId: 'nyzoride-69ab6',
    authDomain: 'nyzoride-69ab6.firebaseapp.com',
    storageBucket: 'nyzoride-69ab6.firebasestorage.app',
    measurementId: 'G-MXG58RQEKP',
  );
}
