// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU4wVEDMHeKTsXA6-IX8kDoIEN0WMJeqY',
    appId: '1:159276101326:web:065461d452842909876a9f',
    messagingSenderId: '159276101326',
    projectId: 'mana-driver',
    authDomain: 'mana-driver.firebaseapp.com',
    storageBucket: 'mana-driver.firebasestorage.app',
    measurementId: 'G-DB7T6D2M2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUFCkp60pYmkP4wOW_S1t-yHV1T_yPH4',
    appId: '1:159276101326:android:1812c85570221b25876a9f',
    messagingSenderId: '159276101326',
    projectId: 'mana-driver',
    storageBucket: 'mana-driver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNa20PzKTCPltG3xx5wE7EnRg0oFYiXhE',
    appId: '1:159276101326:ios:ab4953a6b506ad79876a9f',
    messagingSenderId: '159276101326',
    projectId: 'mana-driver',
    storageBucket: 'mana-driver.firebasestorage.app',
    iosBundleId: 'com.example.nyzoCaptain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNa20PzKTCPltG3xx5wE7EnRg0oFYiXhE',
    appId: '1:159276101326:ios:f3c9ce9af9a00261876a9f',
    messagingSenderId: '159276101326',
    projectId: 'mana-driver',
    storageBucket: 'mana-driver.firebasestorage.app',
    iosBundleId: 'com.example.mdDriverApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU4wVEDMHeKTsXA6-IX8kDoIEN0WMJeqY',
    appId: '1:159276101326:web:5a18e3498800cd77876a9f',
    messagingSenderId: '159276101326',
    projectId: 'mana-driver',
    authDomain: 'mana-driver.firebaseapp.com',
    storageBucket: 'mana-driver.firebasestorage.app',
    measurementId: 'G-WE34WNRZNR',
  );
}
