import 'dart:ui';

const korangeColor = Color(0xFFFF6B00);
const kwhiteColor = Color(0xFFFFFFFF);
const kgreyColor = Color(0xFF9AA9BA);
const kbordergreyColor = Color(0xFFE0E0E0);
const kseegreyColor = Color(0xFF999999);
const korangeBordercolor = Color(0xFFFF892F);
const KorangeLightColor = Color(0xFFFF8A35);
const KnotificationcircleColor = Color(0xFFDAE1E9);
const KdeviderColor = Color(0xFFF3F4F8);
const KbottomnaviconColor = Color(0xFFC5C5C5);
const KgreenColor = Color(0xFF00D458);
const KcardborderColor = Color(0xFFE5E8F3);
const KblackColor = Color(0xFF222222);
const KredColor = Color(0xFFFF4229);
const KorangeColorNew = Color(0xFFFF5100);
const KlightgreyColor = Color(0xFFF3F4F8);
const KaddresscardborderColor = Color(0xFFDCE3EC);
const korangeresponseColor = Color(0xFFFF9D00);
const KcontactcardColor = Color(0xFFFFF4EB);
const KcontactimagecontainerColor = Color(0xFFFFE6D3);
const KcontacttextColor = Color(0xFFFFBE8C);
const KbtngreenColor = Color(0xFF28A745);
const KgreyorangeColor = Color(0xFFFFE5D3);
const kcocoblack = Color(0xFF222222);
const klightorangecolor = Color(0xFFFFEDE1);
const kcirclegrey = Color(0xFFE4F0FE);
